### PR TITLE
Fixes for Audit/Error log

### LINKED ISSUE #190: Admin | display of user privileges
The user administration function isn't displaying the privileges properly. User saves changes, are not updated in the display.

### PR DESCRIPTION
**Pull request by tjwdev**
resolves #190/191/69 + boolean vs Boolean bug
-removed stack traces from error log object returns
-changed data type for boolean aspects of user log
-Make note, for error/audit log returns we actually add days to filter dates, we should look at this more closely.

### CODE REVIEW

**Review by gtasautumn — APPROVED** [review]
when you create the ticket for the boolean issue, pls attach it to the PR so we can track it. Looks good otherwise

**Comment by tjwdev** [comment]
This also resolves #235 under GTAS-UI

**Comment by gtasautumn** [comment]
ha. Forgot the tickets were created on the ui repo.

**Comment by tjwdev** [comment]
Oh no. Ah.. As a clarifying remark ALL ticket numbers in this PR reference GTAS-UI tickets.

**Pull request merged**
